import { ENTERPRISE_TAG, PLATFORM_ROLE } from './role'

export const ROOT_PERMISSION = '*:*:*'

export const ROLE_CODE = {
  superAdmin: PLATFORM_ROLE.superAdmin,
  platformAdmin: PLATFORM_ROLE.platformAdmin,
  auditor: PLATFORM_ROLE.auditor,
  enterpriseDemander: ENTERPRISE_TAG.demander,
  enterpriseProvider: ENTERPRISE_TAG.provider,
  enterpriseServiceProvider: ENTERPRISE_TAG.provider,
  enterpriseLabProvider: ENTERPRISE_TAG.provider,
} as const

export const MENU_CODE = {
  operatorDashboard: 'operator.dashboard',
  operatorBusiness: 'operator.business',
  operatorUser: 'operator.user',
  operatorEnterpriseAudit: 'operator.enterprise-audit',
  operatorDemand: 'operator.demand',
  operatorConsult: 'operator.consult',
  operatorOrder: 'operator.order',
  operatorReport: 'operator.report',
  operatorComment: 'operator.comment',
  operatorMessage: 'operator.message',
  operatorSystem: 'operator.system',
  operatorRole: 'operator.system.role',
  operatorWorkflow: 'operator.system.workflow',
  operatorBaseConfig: 'operator.system.base-config',

  enterpriseDashboard: 'enterprise.dashboard',
  enterpriseProfile: 'enterprise.profile',
  enterpriseDemand: 'enterprise.demand',
  enterpriseOrder: 'enterprise.order',
  enterpriseReport: 'enterprise.report',
  enterpriseMessage: 'enterprise.message',
  enterpriseAccountSettings: 'enterprise.account-settings',
  enterpriseServiceCapability: 'enterprise.service-capability',
  enterpriseServiceProject: 'enterprise.service-project',
  enterpriseOrderReceive: 'enterprise.order-receive',
  enterpriseQualification: 'enterprise.qualification',

  personalDashboard: 'personal.dashboard',
  personalDemand: 'personal.demand',
  personalOrder: 'personal.order',
  personalMessage: 'personal.message',
  personalProfile: 'personal.profile',
  personalEnterpriseUpgrade: 'personal.enterprise-upgrade',
} as const

export const PERMISSION_CODE = {
  operatorDashboardView: 'operator:dashboard:view',
  operatorUserView: 'operator:user:view',
  operatorUserEdit: 'operator:user:edit',
  operatorEnterpriseAuditView: 'operator:enterprise-audit:view',
  operatorEnterpriseAuditApprove: 'operator:enterprise-audit:approve',
  operatorDemandView: 'operator:demand:view',
  operatorDemandAssign: 'operator:demand:assign',
  operatorConsultView: 'operator:consult:view',
  operatorConsultHandle: 'operator:consult:handle',
  operatorOrderView: 'operator:order:view',
  operatorOrderHandle: 'operator:order:handle',
  operatorReportView: 'operator:report:view',
  operatorReportAudit: 'operator:report:audit',
  operatorCommentView: 'operator:comment:view',
  operatorCommentHandle: 'operator:comment:handle',
  operatorMessageView: 'operator:message:view',
  operatorRoleView: 'operator:role:view',
  operatorRoleEdit: 'operator:role:edit',
  operatorWorkflowView: 'operator:workflow:view',
  operatorWorkflowEdit: 'operator:workflow:edit',
  operatorBaseConfigView: 'operator:base-config:view',
  operatorBaseConfigEdit: 'operator:base-config:edit',

  personalDashboardView: 'personal:dashboard:view',
  personalDemandView: 'personal:demand:view',
  personalDemandPublish: 'personal:demand:publish',
  personalDemandEdit: 'personal:demand:edit',
  personalOrderView: 'personal:order:view',
  personalMessageView: 'personal:message:view',
  personalProfileView: 'personal:profile:view',
  personalProfileEdit: 'personal:profile:edit',
  personalEnterpriseUpgradeView: 'personal:enterprise-upgrade:view',
  personalEnterpriseUpgradeSubmit: 'personal:enterprise-upgrade:submit',

  enterpriseDashboardView: 'enterprise:dashboard:view',
  enterpriseProfileView: 'enterprise:profile:view',
  enterpriseProfileEdit: 'enterprise:profile:edit',
  enterpriseDemandView: 'enterprise:demand:view',
  enterpriseDemandPublish: 'enterprise:demand:publish',
  enterpriseDemandEdit: 'enterprise:demand:edit',
  enterpriseDemandHandle: 'enterprise:demand:handle',
  enterpriseOrderView: 'enterprise:order:view',
  enterpriseOrderReceive: 'enterprise:order-receive:view',
  enterpriseOrderHandle: 'enterprise:order:handle',
  enterpriseReportView: 'enterprise:report:view',
  enterpriseReportHandle: 'enterprise:report:handle',
  enterpriseMessageView: 'enterprise:message:view',
  enterpriseAccountSettingsView: 'enterprise:account-settings:view',
  enterpriseServiceCapabilityView: 'enterprise:service-capability:view',
  enterpriseServiceCapabilityEdit: 'enterprise:service-capability:edit',
  enterpriseServiceProjectView: 'enterprise:service-project:view',
  enterpriseServiceProjectManage: 'enterprise:service-project:manage',
  enterpriseQualificationView: 'enterprise:qualification:view',
  enterpriseQualificationSubmit: 'enterprise:qualification:submit',
  enterpriseProviderQualificationSubmit: 'enterprise:provider-qualification:submit',
  enterpriseServiceShelf: 'enterprise:service:shelf',

  contentManageView: 'content:manage:view',
  dictionaryManageView: 'system:dictionary:view',
  workflowManageView: 'workflow:manage:view',
  operationLogView: 'system:operation-log:view',
  dangerousAction: 'system:dangerous:action',

  platformDashboardView: 'operator:dashboard:view',
  userManageView: 'operator:user:view',
  auditEnterpriseQuery: 'operator:enterprise-audit:view',
  auditEnterpriseApprove: 'operator:enterprise-audit:approve',
  demandManageView: 'operator:demand:view',
  consultManageView: 'operator:consult:view',
  orderManageView: 'operator:order:view',
  reportManageView: 'operator:report:view',
  commentManageView: 'operator:comment:view',
  messageManageView: 'operator:message:view',
  roleManageView: 'operator:role:view',

  enterpriseConsultView: 'enterprise:service-project:view',
  enterpriseConsultHandle: 'enterprise:service-project:manage',
  enterpriseServiceView: 'enterprise:service-project:view',
  enterpriseServiceManage: 'enterprise:service-project:manage',
  enterpriseCommentView: 'enterprise:report:view',
  enterpriseCommentManage: 'enterprise:report:handle',
  enterpriseTestingProgressView: 'enterprise:order:view',
  enterpriseDataReportView: 'enterprise:report:view',
  enterpriseDemandHallView: 'enterprise:service-project:view',
} as const

export const LEGACY_PERMISSION_CODE = {
  platformDashboardView: PERMISSION_CODE.operatorDashboardView,
  userManageView: PERMISSION_CODE.operatorUserView,
  auditEnterpriseQuery: PERMISSION_CODE.operatorEnterpriseAuditView,
  auditEnterpriseApprove: PERMISSION_CODE.operatorEnterpriseAuditApprove,
  demandManageView: PERMISSION_CODE.operatorDemandView,
  consultManageView: PERMISSION_CODE.operatorConsultView,
  orderManageView: PERMISSION_CODE.operatorOrderView,
  reportManageView: PERMISSION_CODE.operatorReportView,
  commentManageView: PERMISSION_CODE.operatorCommentView,
  messageManageView: PERMISSION_CODE.operatorMessageView,
  roleManageView: PERMISSION_CODE.operatorRoleView,
} as const
